# we actually need both environments PHP and rvm
# however it is only possible to define the environment for one language
language: php

php:
  - 5.5
  - 5.6
  - 7.0

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0


install:
  - composer install


notifications:
  email:
    - scoutman57@gmail.com