# we actually need both environments PHP and rvm
# however it is only possible to define the environment for one language
language: php

php:
  - 5.5
  - 5.6
  - 7.0

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0


install:
  - composer install

notifications:
  email:
    - scoutman57@gmail.com
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/37efe95843ef4f755625
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false